
#######################
#Internal Server Error
POST /api/v1/technicalViability HTTP/1.1
Content-Type: application/json
Host: 172.30.0.77:8882
Content-Length: 75

{
  "lat": "0",
  "lng": "100",
  "city": "Salto",
  "state": "ckpmcwioecwre"
}


################
#Internal Server Error
POST /api/v1/technicalViability HTTP/1.1
Content-Type: application/json
Host: 172.30.0.77:8882
Content-Length: 83

{
  "lat": "-22.72309",
  "lng": "-47.3701447",
  "city": "Caieiras",
  "state": "SP"
}

#################
#Deu certo
POST /api/v1/technicalViability HTTP/1.1
Content-Type: application/json
Host: 172.30.0.77:8882
Content-Length: 97

{
  "lat": "-22.66894695125081",
  "lng": "-47.69352932190997",
  "city": "Santos",
  "state": "SP"
}

###############
#Deu certo
POST /api/v1/technicalViability HTTP/1.1
Content-Type: application/json
Host: 172.30.0.77:8882
Content-Length: 101

{
  "lat": "-22.675123243125157",
  "lng": "-47.703913865439965",
  "city": "Campinas",
  "state": "SP"
}