#Exemplo de clientes que estão na base de inviabilidade de instalação

#A latitude e longitude são do google maps, com base no endereço.

#Exemplo 1
POST /api/v1/technicalViability HTTP/1.1
Content-Type: application/json
Host: 172.30.0.77:8882
Content-Length: 75

{
  "lat": "-23.980469429294317",
  "lng": "-46.470727845510964",
  "city": "Sao Vicente",
  "state": "SP"
}

###################
#Exemplo 2
POST /api/v1/technicalViability HTTP/1.1
Content-Type: application/json
Host: 172.30.0.77:8882
Content-Length: 75

{
  "lat": "-22.975116274310114",
  "lng": "-47.13466110321248",
  "city": "Campinas",
  "state": "SP"
}

###################
#Exemplo 3
POST /api/v1/technicalViability HTTP/1.1
Content-Type: application/json
Host: 172.30.0.77:8882
Content-Length: 75

{
  "lat": "-22.96599213234043",
  "lng": "-47.201105418558384",
  "city": "Campinas",
  "state": "SP"
}


###################
#Exemplo 4
#Esse deu 500
POST /api/v1/technicalViability HTTP/1.1
Content-Type: application/json
Host: 172.30.0.77:8882
Content-Length: 75

{
  "lat": "-22.840331283099445",
  "lng": "-47.15941573019807",
  "city": "Sumare",
  "state": "SP"
}
