version: "3.0"

services:

  #Serviço do integração do CRM
  go-crm:
    container_name: go-crm
    restart: always
    #A TESTAR AINDA
    env_file: .env
    image: go-crm:dev
    ports:
      - "8080:8080"

  # Grafana para monitormento dos logs do CRM
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_test_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - grafana-net

  #Banco de dados de Log e configuração 
  postgres:
    image: postgres:10.5
    restart: always
    container_name: crm-postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      # - ./postgres-data:/var/lib/postgresql/data
      # Copiando os scripts de create
      - ./postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./postgres/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

networks:
  grafana-net:
    driver: bridge


volumes:
  grafana_test_data:
  postgres: