{
 "title": "1 dashboard",
 "description": "Apenas testando",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Transações por cliente",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select cliente,count(id) from tb_logs group by cliente"
    }
   ]
  },
  {
   "title": "Total de erros",
   "type": "stat",
   "description": "Total de logs com erros de transação",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id) from tb_logs where error = true"
    }
   ]
  },
  {
   "title": "Total de Transações",
   "type": "timeseries",
   "description": "Monitoramento da tabela de logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "rawSql": "SELECT * from tb_logs" }
   ]
  },
  {
   "title": "Agrupamento por tipos de erros",
   "type": "bargauge",
   "description": "Agrupamento por tipo de erros nas transações",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT tabela,message, count(id) from tb_logs group by tabela,message"
    }
   ]
  },
  {
   "title": "Transações por serviço",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select tabela,count(id) as total from tb_logs group by tabela;"
    }
   ]
  }
 ]
}