package cfr

import "time"

type Cfr struct {
	Codigo_pessoa       string
	Tipo                string
	Nome_pessoa         string
	Nome_fantasia       string
	Natureza_pessoa     string
	Cnpj_cpf            string
	Inscricao_estadual  string
	Sitfed              string
	Siticms             string
	Sitipi              string
	Endereco            string
	Numeroend           string
	End_complemento     string
	Bairro              string
	Cidade              string
	Uf                  string
	Cep                 string
	Pais                string
	Telefone_1          string
	Telefone_2          string
	Contato             string
	Email               string
	Emailnfe            string
	Home_page           string
	Nosso_cliente       string
	Categoria_cliente   string
	Cond_pg_padrao_clie string
	Docpadrao_cliente   string
	Cobrpadrao_cliente  string
	Portpadrao_cliente  string
	Status              string
	Data_cad            string
	Zonafranca          string
	Inscricao_suframa   string
	Vendedor1           string
	Comissao1_fat       string
	Transp_padr_clie    string
	Tipo_frete          string
	Endereco_cobranca   string
	Numeroend_cobranca  string
	Bairro_cobranca     string
	Cidade_cobranca     string
	Uf_cobranca         string
	Cep_cobranca        string
	Data_hora_inclusao  time.Time
	Usuario_inclusao    string
	Data_hora_alteracao time.Time
	Usuario_alteracao   string
	Ende_latitude       string
	Ende_longitude      string
	Origem              string
}
